l="4"
m="3"
n="2.5"

t="-51"
u="39"
v="65"

out="gupta123.iv"

CG_hw5: CG_hw5c
	@java -cp CG_hw5_classes Main $(l) $(m) $(n) $(t) $(u) $(v) $(out)

CG_hw5c:
	@javac CG_hw5_java/*.java -d CG_hw5_classes

clean:
	@rm -rf CG_hw5_classes/*
